/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#76331b",
        "on-primary": "#5d1900",
        "outline": "#a98a80",
        "error-container": "#93000a",
        "surface-tint": "#ffb59d",
        "on-secondary-fixed": "#390c00",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#390c00",
        "tertiary": "#59d5fb",
        "secondary": "#ffb59d",
        "primary-container": "#ff6b35",
        "on-surface": "#e5e2e1",
        "background": "#131313",
        "tertiary-fixed-dim": "#59d5fb",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#fb9d7d",
        "error": "#ffb4ab",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#e1bfb5",
        "on-tertiary-fixed": "#001f28",
        "on-error": "#690005",
        "surface-dim": "#131313",
        "surface-container": "#201f1f",
        "on-secondary": "#581d07",
        "primary-fixed-dim": "#ffb59d",
        "tertiary-fixed": "#b5ebff",
        "outline-variant": "#594139",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-container": "#003744",
        "on-primary-fixed-variant": "#832600",
        "secondary-fixed": "#ffdbd0",
        "primary-fixed": "#ffdbd0",
        "on-secondary-fixed-variant": "#76331b",
        "inverse-primary": "#ab3500",
        "tertiary-container": "#00a7cb",
        "surface-variant": "#353534",
        "primary": "#ffb59d",
        "on-background": "#e5e2e1",
        "secondary-fixed-dim": "#ffb59d",
        "on-tertiary-fixed-variant": "#004e60",
        "inverse-on-surface": "#313030",
        "on-tertiary": "#003543",
        "on-primary-container": "#5f1900",
        "surface-bright": "#3a3939",
        "surface-container-highest": "#353534",
        "surface": "#131313",
        "surface-container-high": "#2a2a2a"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
